Repository zilliztech/spark-milvus, pull requests merged in 2025-03, with the labels that each got.

#38 Add TLS/mTLS Support for Milvus Connection
  src/main/scala/zilliztech/spark/milvus/MilvusConnection.scala
  src/main/scala/zilliztech/spark/milvus/MilvusOptions.scala
Labels: lgtm, approved, size/M

#36 Convert backup data to Parquet.
  examples/pom.xml
  examples/src/main/scala/BackupToParquetDemo.scala
  pom.xml
  src/main/java/com/zilliztech/spark/l0data/DataType.java
  src/main/java/com/zilliztech/spark/l0data/DeltaData.java
  src/main/java/com/zilliztech/spark/l0data/DeltaLogExample.java
  src/main/java/com/zilliztech/spark/l0data/DeltaLogReader.java
  src/main/java/com/zilliztech/spark/l0data/DeltaLogSparkExample.java
  src/main/java/com/zilliztech/spark/l0data/DeltaLogUtils.java
  src/main/java/com/zilliztech/spark/l0data/DescriptorEvent.java
  src/main/java/com/zilliztech/spark/l0data/DescriptorEventData.java
  src/main/java/com/zilliztech/spark/l0data/DescriptorEventHeader.java
  src/main/java/com/zilliztech/spark/l0data/EventHeader.java
  src/main/java/com/zilliztech/spark/l0data/EventType.java
  src/main/java/com/zilliztech/spark/l0data/FileReadSeeker.java
  src/main/java/com/zilliztech/spark/l0data/IndexFileEventData.java
  src/main/java/com/zilliztech/spark/l0data/Int64PrimaryKey.java
  src/main/java/com/zilliztech/spark/l0data/Int64PrimaryKeys.java
  src/main/java/com/zilliztech/spark/l0data/ParquetPayloadReader.java
  src/main/java/com/zilliztech/spark/l0data/PrimaryKey.java
  src/main/java/com/zilliztech/spark/l0data/PrimaryKeys.java
  src/main/java/com/zilliztech/spark/l0data/README.md
  src/main/java/com/zilliztech/spark/l0data/ReadSeeker.java
  src/main/java/com/zilliztech/spark/l0data/StringPrimaryKey.java
  src/main/java/com/zilliztech/spark/l0data/StringPrimaryKeys.java
  src/main/java/com/zilliztech/spark/l0data/VarCharPrimaryKey.java
  src/main/java/milvus/proto/backup/Backup.java
  src/main/proto/backup.proto
  src/main/resources/l0_delta_log_for_testing
  src/main/resources/log4j.properties
  src/main/resources/simplelogger.properties
Labels: lgtm, approved, size/XXL

#40 add support for aliyun oss
  examples/pom.xml
  examples/src/main/scala/BackupFileUtils.scala
  examples/src/main/scala/BackupProcess.scala
  examples/src/main/scala/BackupToParquetDemo.scala
  examples/src/main/scala/L0SegmentUtils.scala
  pom.xml
  src/main/java/com/zilliztech/spark/l0data/DeltaLogReader.java
  src/main/java/com/zilliztech/spark/l0data/DeltaLogUtils.java
  src/main/java/com/zilliztech/spark/l0data/FileReadSeeker.java
  src/main/java/com/zilliztech/spark/l0data/L0segmentUtils.java
Labels: size/XL

#39 updating quickstart files with tls and mtls connection params
  examples/py/quickstart.py
  examples/src/main/scala/QuickStart.scala
Labels: lgtm, approved, size/S
